version: '3.7'

services:
  backend:
    build:
      context: ./
    command: gunicorn sizakat.wsgi --bind 0.0.0.0:8000 --log-file -
    volumes:
      - ./:/app/backend/
    ports:
      - ${BACKEND_PORT:-8000}:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env

volumes:
  postgres_data:
