version: '3.7'

services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - ${BACKEND_PORT:-8000}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/var/www/html/static/
    depends_on:
      - backend

  backend:
    build:
      context: ./
    restart: always
    command: gunicorn sizakat.wsgi --bind 0.0.0.0:8000 --log-file -
    volumes:
      - ./:/app/backend/
      - staticfiles:/app/backend/staticfiles/
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  staticfiles:
